
services:
  alpine-base-hl:
    build: .
    image: hackinglab/alpine-base-hl:3.2
    environment:
      - HL_USER_USERNAME=hacker
      - HL_USER_PASSWORD=compass
      - GOLDNUGGET=FLAG{hl-smoke-test}
