FROM alpine:3.16
LABEL maintainer="Ivan Buetler <ivan.buetler@compass-security.com>"

# Add s6-overlay
ENV S6_OVERLAY_VERSION=v3.2.1.0

RUN set -eux; \
	apk add --update --no-cache bind-tools curl libcap bash net-tools openssl pwgen xz && \
	apk upgrade --available && \
	curl -fsSL "https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" | tar -Jxpf - -C /  && \
	curl -fsSL "https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-i686.tar.xz" | tar -Jxpf - -C /  && \
	rm -rf /var/cache/apk/*

COPY root /

ENTRYPOINT ["/init"]
CMD []
